language: python
sudo: required
dist: xenial
python:
  - '3.6'
  - '3.7'
before_install:
  - sudo apt-get install -y blender
script: python setup.py test
before_deploy: python setup.py sdist bdist_wheel
deploy:
  - provider: pypi
    skip_cleanup: true
    skip_existing: true
    on:
      tags: true
      repo: Moguri/panda3d-blend2bam
      python: '3.7'
    user: Moguri
    password:
      secure: cPj9ksZTmc04S4NOszdIV39R2XNTJbeppCkVlOrowgG0nAOD08jUiZo0NAjqK4Sb6zWiEPByiGKjmes1xfF6vca/3RsV/TrUQVOjd0V1EuNkdTOlPdsMiBrmFmj0ekNwIjQyqsmUGwYLbytzRcP3wA255md6oCuf9jsNU8ZZqW4fjmOs8XNGJUDw7SijDmjC7EMSrxr6zFOMCI8xQQsn/Nx/M2M+j3a3hbxoMC+01bTwvMdC/eYBduyk0aI8pnX/q75DjLGXssz0tU/e3Wl9BhmSirw3X31ZhzovWuyqzPuBdK8BwHpW6uXTEMLOj1SZPPlsvKH9Jcq5XquBAEUZaLBcTrSb98q7S9hds/ht6sSmj+40KrD8pGGstn4cf9HKBCwWSY8O/3bduvvpeRqUeFKHfHwtZSE6LF+U5cYRt+cJ4IVJcg0sl6wCrc8UndOuO78OS4ynfj4SNk+eEKlGu7CDRb9l5Ptnpqe0dB0Pelji/6zHxfd2yDB6+UOrWCe0xKwG6g1tpnS/La+TMjCllBYBsCWo/FsUyTdZjx3QjMRjjRjPwzJZ3VXAnnTuonow7n15+tD8pUCURjOVE/G6kMalHHzMfoIGNq8wssOEy4ZKgAk0B8UjorMLUu+FjnFFI/D6eXp6W0cc7So7xNkZap5DJAd9jV//Imf+qy4Kzys=
    distributions: sdist bdist_wheel
  - provider: releases
    on:
        tags: true
        repo: Moguri/panda3d-blend2bam
        python: '3.7'
    skip_cleanup: true
    api_key:
        secure: Cqi4CfzOfZdjqPMw3t2zsU4da3Qp9prqXfBrmzVli5qlzZUjbwgII0++bX9OOKBv+cCjzzES5wf1iegpso5ygw+jlr4c5qix3+B3V7jDzGJ9+tqtUPyu+sn65yVA2P8Tg5OYJ1Txe9APVdnpxY2qHWl4zSaNsWCOZwU06nNpjUy3/01pOl9yxW80X3zmhjO2YCRiNfErxMa6q6n+wSmky3aQgwawgjkJyvjSOYb6qLMV+BLVP31pi/IDQXN3gRxqnpfN9NP/8xlyV+YJI81sWK3rVds2/RGBZbBldc0cqkig99EmN/J4ijjqil8q2d2cyKOeHFzswc/fMN+0EqMXpe0J+PFuowPSKQXqHGlDfRd499LwSC8CeSjBU7AYhBaXDpfj7kLBpdz8YBcijm4t2Zn5BbTOcKhkK+LUiz5c98jC6ZWivjJdqirIoUkd8yVkE8rythSXKbyyniLAK6XeLHxIdATVHf8/lGM+7kF5N6dti6IgThT+bgh0G/XQp3pHveGs1t5EaT1mXYP8fVlxwiSHPJKT0z0siv+RUYjvLvIGiaPlZGKTR4tFPbID3snPR0KKwzNLZsgS5yiQyriI9dIEEPpHjK28jp53gYysE5r/yBr+k7gJxOmNjwpIV7NEvLjeQgb8lCT2zXhFHrrnkM+7oMnJSLs0nV4sDjc5vm0=
    file_glob: true
    file: dist/*
